export { default as Home } from './Home'
export { default as Crops } from './Crops'
export { default as Prediction } from './Prediction'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
